name: ytshot
region: sfo
services:
- build_command: yarn build
  environment_slug: node-js
  github:
    branch: main
    deploy_on_push: true
    repo: gourab28/Ytshot
  http_port: 8001
  instance_count: 1
  instance_size_slug: basic-xxs
  name: ytshot
  routes:
  - path: /
  run_command: yarn start
  source_dir: /
